### ISSUE TITLE
O diretório "node_modules" deve estar no ".gitignore"

### ISSUE THREAD

**Issue by edysegura** [WBorsato/TrabalhoDM124#1]
![image](https://user-images.githubusercontent.com/5324414/71944631-2ba6bf80-31a3-11ea-8393-a46e3cd5baed.png)

**Comment by WBorsato** [comment]
https://github.com/WBorsato/TrabalhoDM124/commit/1e86bd9687c8d6ad258b093e86a7d34739950218
