### ISSUE TITLE
Essa rota deveria ser renomeada para "/api/deliveries" ou "/api/entregas"

### ISSUE THREAD

**Issue by edysegura** [WBorsato/TrabalhoDM124#2]
https://github.com/WBorsato/TrabalhoDM124/blob/9688f849f9c9f88550c4ad03b61f63ce33d3953f/src/app.js#L19

**Comment by WBorsato** [comment]
https://github.com/WBorsato/TrabalhoDM124/commit/1e86bd9687c8d6ad258b093e86a7d34739950218
