### ISSUE TITLE
É interessante retornar os dados cadastrados na resposta da requisição com o id gerado

### ISSUE THREAD

**Issue by edysegura** [WBorsato/TrabalhoDM124#4]
![image](https://user-images.githubusercontent.com/5324414/71945019-5b09fc00-31a4-11ea-9395-25303795054d.png)

**Comment by WBorsato** [comment]
Please check https://github.com/WBorsato/TrabalhoDM124/commit/1e86bd9687c8d6ad258b093e86a7d34739950218
